---
- name: Configurar un VPN Server L2TP/IPsec en Windows Server 2022
  hosts: windows
  gather_facts: no
  vars:
    l2tp_psk: "TuClaveSuperSecreta123"
    rras_service_name: "RemoteAccess"
    vpn_interface: "Ethernet"

  tasks:

  - name: Instalar funciones necesarias para RRAS
    ansible.windows.win_feature:
      name:
        - RemoteAccess
        - Routing
        - DirectAccess-VPN
      state: present
      include_management_tools: yes

  - name: Habilitar reenvío IP en el registro
    ansible.windows.win_regedit:
      path: HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters
      name: IPEnableRouter
      data: 1
      type: dword

  - name: Configurar clave precompartida (PSK) para IPsec
    ansible.windows.win_command: >
      powershell -Command "Set-VpnServerConfiguration -L2tpPsk '{{ l2tp_psk }}' -PassThru"
    args:
      creates: C:\VPN_PSK_configured.txt

  - name: Crear archivo de marca para PSK
    ansible.windows.win_file:
      path: C:\VPN_PSK_configured.txt
      state: touch

  - name: Configurar RRAS para VPN con L2TP
    ansible.windows.win_command: |
      powershell.exe -Command "Install-RemoteAccess -VpnType Vpn"
    args:
      creates: C:\RRAS_configured.txt

  - name: Crear archivo de marca para RRAS
    ansible.windows.win_file:
      path: C:\RRAS_configured.txt
      state: touch

  - name: Iniciar y habilitar el servicio RRAS
    ansible.windows.win_service:
      name: "{{ rras_service_name }}"
      start_mode: auto
      state: started

  - name: Abrir puertos necesarios en el Firewall de Windows (L2TP/IPsec)
    ansible.windows.win_firewall_rule:
      name: "Allow VPN L2TP/IPsec"
      enable: yes
      direction: in
      action: allow
      protocol: udp
      localport: 
        - 500
        - 1701
        - 4500

  - name: Permitir protocolo ESP (IPsec)
    ansible.windows.win_shell: >
      New-NetFirewallRule -DisplayName "Allow ESP (IPsec)" -Direction Inbound -Protocol 50 -Action Allow

  - name: Permitir tráfico WinRM para gestión remota (opcional)
    ansible.windows.win_firewall_rule:
      name: "Allow WinRM"
      enable: yes
      direction: in
      action: allow
      protocol: TCP
      localport: 5986

  - name: Verificar estado de RRAS
    ansible.windows.win_service_info:
      name: "{{ rras_service_name }}"
    register: rras_status

  - name: Mostrar estado del servicio RRAS
    debug:
      msg: "Estado del servicio RRAS: {{ rras_status.status }}"

  - name: Reiniciar el servidor si se requiere
    ansible.windows.win_reboot:
      reboot_timeout: 600
      msg: "Reinicio para completar la configuración del servidor VPN L2TP/IPsec"